# Generated by Django 4.1.5 on 2023-01-19 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='authors.author')),
                ('poem_favorites', models.ManyToManyField(blank=True, related_name='poem_favorites', to=settings.AUTH_USER_MODEL)),
                ('poem_likes', models.ManyToManyField(blank=True, related_name='poem_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
